version: "3"
services:
  iemaps_frontend:
    container_name: iemaps_react
    build:
        context: ../
        dockerfile: deployments/react/dockerfile
    ports:
      - "3000:3000"    
      
  iemaps_backend:
    container_name: ieMaps_flask
    build: 
      context: ../
      dockerfile: deployments/flask/dockerfile
    ports: 
      - "5000:5000"
