# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /react

# add `/app/node_modules/.bin` to $PATH
ENV PATH /react/node_modules/.bin:$PATH

# install and cache app dependencies
COPY react/package-lock.json /react/package-lock.json
#COPY . ./
RUN npm install --silent
#RUN npm install react-scripts@3.0.1 -g --silent

# start app
CMD ["npm", "start"]