# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /react

# add `/app/node_modules/.bin` to $PATH
ENV PATH /react/node_modules/.bin:$PATH

COPY react/* /react/

RUN npm install --silent

# start app
CMD ["npm", "start"]